title: generic-web-dev-offline
hero_image: images/banner.png
description: generic-web-dev-offline description
version: 4
listed: false
copyedit: false
last_tested: "2019-01-31"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
