title: generic-web-dev-offline
hero_image: images/banner.png
description: Working offline with HTML, CSS and Javascript
version: 4.0.0
listed: false
copyedit: false
ingredient: true
technologies: "html, css, javascript"
last_tested: "2019-01-31"
steps:
  - title: Working offline with HTML, CSS and Javascript